# Please ping balenaCI team when you decide to edit this this.
# This configuration is at the deprecation stage, and the team needs to see what use cases
# are tried to be solved with it.

---
npm:
  platforms: []

docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: node-loki-grpc-client
      publish: false
