version: '2.1'

services:
  loki:
    image: grafana/loki:1.5.0
    ports:
      - '9095:9095'
  sut:
    build: .
    depends_on:
      - loki
    command: ['npm', 'test']
    environment:
      LOKI_HOST: 'loki'
